FROM node:alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

FROM node:alpine AS runner
WORKDIR /app

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

COPY --chown=nextjs:nodejs . .
COPY --chown=nextjs:nodejs /.next ./.next

USER nextjs

EXPOSE 3000

CMD ["yarn", "dev"]
